[package]
name = "rs-longs2bin"
version = "0.1.0"
edition = "2024"

description = "Converts long integers to binary format."
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-longs2bin"
homepage = "https://github.com/takanoriyanagitani/rs-longs2bin"
documentation = "https://docs.rs/rs-longs2bin/latest"
keywords = ["binary", "integer", "long", "convert"]

exclude = [
]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"

[[bin]]
name = "longs2bin_std"

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1
